### ISSUE TITLE
add socket support (alfred)

### ISSUE THREAD

**Issue by kokel** [ffnord/ffmap-backend#30]
Hello,

recently the alfred daemon has been patched to support the configuration for the unix socket path: [Link](http://git.open-mesh.org/alfred.git/commit/6c6a6f735054a839bd809d5711c29287505ccdd5)

After this the alfred client ```alfred-json``` has also been patched to support this: [Link](https://github.com/tcatm/alfred-json/commit/acfff244a2b335318045fb7faedd8c42dce09e71#diff-d41d8cd98f00b204e9800998ecf8427e)

This allows communities which have currently multiple batman_adv mesh clouds on the same gateway to run one alfred daemon instance for each of the cloud. One implication is that all alfred clients have to patched in order to connect to the correct socket.

So please add support in ffmap-backend for this. Finally, ```bat2nodes.py``` should be called with a new command-line-option like ```-u | --unix-path``` (alfred daemon style) or ```-s | --socket``` (alfred client ```alfred-json``` style) in order to return the wanted unix socket to ```alfred.py``` and ```batman.py``` to make in the ```mkmap.sh``` magically stuff like:

```
./bat2nodes.py -A -s /var/run/alfred0.sock -a somealiases.json -m bat0 -d $DEST
./bat2nodes.py -A -s /var/run/alfred1.sock -a somealiases.json -m bat1 -d $DEST
./bat2nodes.py -A -s /var/run/alfred2.sock -a somealiases.json -m bat2 -d $DEST
```

And some time later someone should make some brainwork to consider the implications supporting multiple batman_adv mesh clouds in one single map, like e.g. duplicate gateways, vpn links?, etc.

**Comment by tcatm** [comment]
This is now implemented.

**Comment by kokel** [comment]
Thanks for the implementation. But as I mentioned above the alfred socket has also be passed to batadv-vis "-u".
