### ISSUE TITLE
Backend Error

### ISSUE THREAD

**Issue by sap-dev** [ffnord/ffmap-backend#69]
Hi,

nachder Installation erhalten wir folgenden Fehler bei der Ausführung des Crons:
```
Traceback (most recent call last):
  File "./backend.py", line 185, in <module>
    main(options)
  File "./backend.py", line 117, in main
    graph.import_vis_data(batadv_graph, nodedb['nodes'], vd)
  File "/root/ffos/ffmap-backend/lib/graph.py", line 17, in import_vis_data
    *zip(*chain(nodes_a, nodes_b))))
TypeError: map() must have at least two arguments.
```

**Comment by jplitza** [comment]
Ich habe nicht die geringste Ahnung, wie dieser Fehler zu Stande kommen könnte. Welchen Commit genau habt ihr ausgecheckt? Direkt in den darüberliegenden Zeilen (15 und 16) ist nämlich in beiden Branches das erste Argument an `map()`, sodass diese Meldung für mich überhaupt keinen Sinn ergibt.

**Comment by jplitza** [comment]
Hm, on second thought, this is probably triggered when both `nodes_a` and `nodes_b` are empty and thus `*zip(*chain(nodes_a, nodes_b))` is empty.
This indicates empty `vis_data`, which in turn supposes that `batadv-vis -i <mesh_interface> -f json` outputs nothing or an error. Is that true? If so, you probably need to start a `batadv-vis` server on the machine running ffmap-backend.

**Comment by AiyionPrime** [comment]
Had the same error,
even since the same day.
But (re)starting vis solved it for me.

**Comment by jplitza** [comment]
Closing this for now, as it seems to have nothing to do with ffmap-backend. If you disagree or the problem is not solved by restarting or properly configuring batadv-vis, i.e. if `batadv-vis -i <mesh interface> -f json` outputs something reasonable, please reopen.
