### ISSUE TITLE
y-labels unreadable on node with many clients

### ISSUE THREAD

**Issue by ecsv** [ffnord/ffmap-backend#84]
It was noticed on the meshviewer installation of Freifunk Chemnitz that the nodes with a large number of clients have overlapping y-labels. This was caused by the '-y 1:1' setting for rrdtool

![tietz_default_settings](https://cloud.githubusercontent.com/assets/1094579/16169879/f5f8e188-353e-11e6-875d-f5b47778a391.png)

This made them remove this setting. The result looked fine for these nodes.

![tietz](https://cloud.githubusercontent.com/assets/1094579/16169921/8aafdab0-3540-11e6-9a37-eca182dd1790.png)

But nodes with a smaller number of nodes started to have fractional part

![test](https://cloud.githubusercontent.com/assets/1094579/16169932/d0b3b1b2-3540-11e6-95ff-6ab8cc346474.png)

This freaked out some people and thus I've started to play around with the setting. @simonwunderlich looked at them and told me that '-Y' seemed to look better to him. Here are the previous examples with '-Y' instead of '-y 1:1'

![tietz_better_settings](https://cloud.githubusercontent.com/assets/1094579/16169943/21ae014e-3541-11e6-920f-f47a2f338e79.png)
![test_better_settings](https://cloud.githubusercontent.com/assets/1094579/16169945/25be5cca-3541-11e6-8430-2b497524540a.png)

It is far from perfect but at least doesn't seem to discriminate any of my examples in favor of the other one. Maybe '-Y' could replace '-y 1:1' in lib/NodeRRD.py. But I would like to get more opinions (or better solutions) before a pull request is made.

----

@ambassador86 @deusama This seems to be relevant for you because it is about your server

**Comment by jplitza** [comment]
Sounds good to me. For the sake of completeness, here's what `rrdgraph(1)` has to say about `-Y`:

> Place the Y grid dynamically based on the graph's Y range. The algorithm ensures that you always have a grid, that there are enough but not too many grid lines, and that the grid is metric. That is the grid lines are placed every 1, 2, 5 or 10 units. This parameter will also ensure that you get enough decimals displayed even if your graph goes from 69.998 to 70.001.  (contributed by Sasha Mikheev).

**Comment by jplitza** [comment]
I merged the corresponding part from #86, thus closing.
