### ISSUE TITLE
usability: averaging of client number confuses users

### ISSUE THREAD

**Issue by ecsv** [ffnord/ffmap-backend#85]
Some users of the meshviewer installation from Freifunk Chemnitz seemed to be very confused by fractional numbers for connected clients. It doesn't seem to be easy to understand that the shown values are averages over a timespan.

I personally have no real problem with the current way things are shown. But the persons which had a problem with the current way it is shown haven't yet followed my suggestion to discuss their problems with the presentation with upstream. So I try to step in here to get a discussion with upstream going. Hopefully, some of the other people join the discussion

Right now a node for example looks like this:

![test](https://cloud.githubusercontent.com/assets/1094579/16170027/142a0164-3544-11e6-9648-99ca390a8c37.png)

The fractional parts could easily be removed again by a rounding function like CEIL for the client number

    rrdtool 'graph' /opt/freifunk/meshviewer/data/nodes/test_ceil.png \
        '-s' '-7d' \
        '-w' '800' \
        '-h' '400' \
        '-Y' \
        'DEF:clients=/opt/freifunk/meshviewer/data/nodedb/a0f3c1984ca8.rrd:clients:AVERAGE' \
        'DEF:upstate=/opt/freifunk/meshviewer/data/nodedb/a0f3c1984ca8.rrd:upstate:AVERAGE' \
        'VDEF:maxc=clients,MAXIMUM' \
        'CDEF:c=0,clients,ADDNAN,CEIL' \
        'CDEF:d=upstate,UN,0,upstate,IF,0,EQ,clients,UN,MAX,maxc,UN,1,maxc,IF,CEIL,1,MAX,*' \
        'AREA:c#0F0:up\\l' \
        'AREA:d#F00:down\\l' \
        'LINE1:c#00F:clients connected\\l'

![test_ceil](https://cloud.githubusercontent.com/assets/1094579/16170034/66105064-3544-11e6-8bb0-bcf9718c11ef.png)

This is just an adjustment in the representation. But for example @simonwunderlich seemed to like the idea more to change the CF settings of the clients RRA in lib/NodeRRD.py to MAX. I personally haven't tested this yet but this could also be a way to represent the number of simultaneously connected clients without ending up with fractional clients.

Maybe this was already discussed in the past or someone else has a better idea how to represent clients with the currently available data.

----

@ambassador86 @deusama This could be relevant for you because it is about data from your server

**Comment by jplitza** [comment]
I feel like neither MAX nor CEIL is the right thing to use, because having a bunch of clients connected for some seconds because a tram rushed by isn't that interesting. Regrettably, rrdtool doesn't have a generic ROUND function as it seems, which would be more appropriate. But the best solution might be to clearly point (in a legend or title) out that these numbers are 1-hour-averages.

**Comment by ecsv** [comment]
Thanks for the feedback.

To the rounding function: This can be implemented implement with existing rrdtool instructions because we only expect positive numbers (including zero) of client:

    'CDEF:c=0.5,clients,ADDNAN,FLOOR'

**Comment by jplitza** [comment]
Yes, of course. I probably should have slept more. Well then, I would prefer rounding over ceiling or flooring, but still vote for simply pointing out that these are rounded values. Any other opinions?

**Comment by ecsv** [comment]
@simonwunderlich Please check these suggestions and discuss them with the people also having problems interpreting the graph

**Comment by simonwunderlich** [comment]
Thank you for bringing that up! My personal first thought was if the graph even shows clients, or if it is some kind of "mixed graph" which shows multiple information (clients, up/down speed, etc) at the same time. The fractions let me think that it must be throughput speeds, not clients that have been shown there, but that was obviously wrong. :)

So I definitely agree to only show integers only, not fractions/real numbers to make that clear. I think we don't need to add a lot of explanation text, but what we could do for clarification is to change the "up" and "down" to "router online" and "router offline".

Also, my personal opinion on round vs ceil vs floor would be ceiling. If you consider a router which had one client at some time, which would lead to an average of 0.1 for example, we would only see this with ceiling, and I think this would preferable.

I'll also bring this discussion to the attention of our group, maybe there are more comments.

Thanks again for taking care of that!

**Comment by ecsv** [comment]
FFV/FFC stopped using the rrdtool for generating the graphs. Also no one else from the original persons who started the discussion contributed anything here. So I am closing it now
